version: '3.1'

services:
  playground:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - './src:/usr/src'
    ports:
      - '8000:8000'
    stdin_open: true
    tty: true